### ISSUE TITLE
[Security Question] Safe to use config structure

### ISSUE THREAD

**Issue by lgarro** [wellyshen/react-cool-starter#100]
Is it safe to use the config structure to store integration keys and such , or do you recommend using another method?

Thanks

**Comment by wellyshen** [comment]
@lgarro I don't think it's safe to store keys in the config file (client-side). If I were you I will have an end point that returns this kind of config (store sensitive data on server-side).

**Comment by jmsherry** [comment]
It might not matter if they're public keys - e.g. Stripe Public Key, but any server/private keys you're better off keeping in environment variables (preferably injected from a safe store, like AWS Parameter Store). I don't think it's a great idea to bake them into the container either FWIW.

**Comment by lgarro** [comment]
Thanks for the replies. I'll give a try those options you mentioned

**Comment by martin2786** [comment]
@jmsherry +1 to that suggestion. @lgarro you can also try using an environment file as discussed in another issue, you can take a look at https://github.com/motdotla/dotenv to see how that works. Remember that your server needs to be secure in order to store keys in a file (the file shouldn't be accessible from the outside world by any means), but at that point it is as safe as any other solution.
