### ISSUE TITLE
matchPath didn't work if we pass query params

### ISSUE THREAD

**Issue by forwardomg** [wellyshen/react-cool-starter#118]
Hey @wellyshen :)
When passing query params to the URL I encountered a problem, the matchPath function doesn't work in this case. A solution is simple, just putting request.path into matchPath instead of request.url. Is it possible that I missed something?

**Comment by wellyshen** [comment]
@forwardomg Here's a [way](https://codeburst.io/react-router-v4-unofficial-migration-guide-5a370b8905a#27d7) for parse query parameters by React-Router v4.

**Comment by forwardomg** [comment]
@wellyshen Yeap, I know how to parse query parameters. My English not so great, so probably I poorly explained the problem.

For example, I have the path like so "/user/1", on the server "loadData" starts to fetch user data because "matchPath" worked well, but if someone request "/user/1?param=1, matchPath cant match these URL addresses so the "loadData" won't work and server won't  be able to fetch data.

**Comment by iamacup** [comment]
Hey @forwardomg thanks for pointing this out - it is important to fix this because external websites will reference you with UTM parameters and the like - which as you say breaks the loadData for server side rendering.

I have fixed this in my version with this commit: https://github.com/iamacup/sliips-ui/commit/c15cf0c2925b16f22740eb674d4e2fbe65d812bc

I changed this line in server.js:

`const match = matchPath(req.url, route);`

to this:

`const match = matchPath(req.path, route);`

what I don't know is if we need to also change this line: `<StaticRouter location={req.url} context={routerContext}>` or anything else - @wellyshen will need to advise as I really don't know about the router :)

**Comment by wellyshen** [comment]
Hi Guys,

I did some survey, there's no specific solution on sever-side for this issue. I think your solution might be OK. But, I'm wondering why use `req.path` instead of `req.url` can work? Can you guys explain the flow or something for me?

BTW, `<StaticRouter location={req.url} context={routerContext}>`, it works fine as the [way](https://codeburst.io/react-router-v4-unofficial-migration-guide-5a370b8905a#27d7) to parse query on client-side.

**Comment by iamacup** [comment]
This is my use case:

I have a route like this:

  ```
{
    path: '/get-started/:id',
    exact: false,
    component: GetStartedPage,
    loadData: (dispatch, params, cookies) => Promise.all([
      dispatch(doLoginWithCookieData(cookies.authentication)),
      dispatch(wizzardDoFetchData(cookies.authentication, Number.parseInt(params.id, 10), null, false)),
    ]),
  }
```

which means this link will work, and the **loadData** method will run from **server.js** - `www.sliips.com/get-started/2`

`matchPath('/get-started/2', route) - **SUCCESS**`

If i post this link to something like medium.com - the link will automatically get converted to something like this: `www.sliips.com/get-started/2?utm_content=comments&utm_medium=hot&utm_source=medium&utm_name=blog-post`

When someone visits the page with all the UTM tags on it - the page will load, but the server will not have run any of the **loadData** items because it could not match against them in **matchPath,** so it will fall to the client to execute the **loadData** methods in the **componentDidMount** or path React lifecycle methods.

`matchPath('/get-started/2?utm_content=comments&utm_medium=hot&utm_source=medium&utm_name=blog-post', route) - **FAIL - there is no match here**`

The solution is to pass the **path** to the **matchPath**, so the server knows what page it is on - basically matchPath does not strip any query parameters in the URL and so any loadData methods won't work if there are query paramters on the **req.url** string.

Does that help explain what we are doing?

**Comment by wellyshen** [comment]
@iamacup Did you mean, if an URL with UTM parameter that use `matchPath(req.url, route)` with `loadData` will cause api fetching failure? Because of `req.url` including the UTM parameter?

**Comment by forwardomg** [comment]
@wellyshen Won't be fetching if URL has at least one query parameter.

**Comment by iamacup** [comment]
Yep - the API call does not happen at all because matchPath can not find a matching route

try this:

http://localhost:3000/UserInfo/4
http://localhost:3000/UserInfo/4?thisVariable=ThisValue

the second one does not provide the API response in the server side render and instead the client has to make the API call.

**Comment by wellyshen** [comment]
OK, I think I should fix this issue for `matchPath()`. Thank you guys :)
