### ISSUE TITLE
Missing main js file. In webpack-assets.json after production build.

### ISSUE THREAD

**Issue by blesSmePadre** [wellyshen/react-cool-starter#125]
At first, mate, thank you for this wonderful boilerplate. May be i didn't understand something clearly while reading README. But if i run production build, main js file isn't generated in webpack-assets.json file. 
Like: 
`"javascript": {}`

Is it normal? Or may be i have some problems with my result build? Thanks in advance)

**Comment by wellyshen** [comment]
@blesSmePadre Yes, because I enable the `deleteOriginalAssets` from `compression-webpack-plugin`. But don't worry, the plugin will help us handle the `.js` assets automatically. If you need it you can keep the original assets by disable the `deleteOriginalAssets` from [here](https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/config.babel.js#L92)

**Comment by ghost** [comment]
Hi, @wellyshen.
I have the same issue.

Due to the fact that in webpack-assets.js "javascript" section is empty - as a result of the SSR html not contained main.js in any form. And when I click to any link, the page is reloaded completely.

When I disable compression-webpack-plugin - production build is correct. 
Router starts to work on the client side.

**Comment by Rid** [comment]
@wellyshen this is happening for me also setting `deleteOriginalAssets: false,` makes production mode usable.

**Comment by wellyshen** [comment]
Hi Guys, this issue has be fixed by the latest version.
