### ISSUE TITLE
Problem wit nodemon

### ISSUE THREAD

**Issue by maximusnikulin** [wellyshen/react-cool-starter#18]
I have a problem with nodemon. I think it's very important to use only webpack for rebuilding components and style for them. I decided to turn off stylelinter and take control of writing my styles by myself. Hovewer, when I wrote code like that :
`@import '../../theme/variables'
body {
  background-color: $color-dark-gray;
  font-family: 'Helvetica-Light', Helvetica, Arial, sans-serif;
}`, where it lacks semicolons after import of file, I got follow message in terminal:
`[nodemon] app crashed - waiting for file changes before starting...`.
The only way to repair it - to execute "rs" for reload server but it's too long.
I suspect that it happens because of WebpackIsomorphicTools, maybe it'll be better to use a classic webpack way as mentioned [here](https://github.com/halt-hammerzeit/universal-webpack)? Or don't use it in development mode.
Thanks.

**Comment by wellyshen** [comment]
@maximusnikulin I think it's not the problem of nodemon, if you use `node index.js` instead of `nodemon index.js` through the `npm start` script, you will see the server stopped due to the error which you have demonstrated. In that situation, even hot reloading can't work, so you must fix the error and restart the server :)

**Comment by maximusnikulin** [comment]
Thanks for your answer, I'll try to find the reason of it.

**Comment by maximusnikulin** [comment]
@wellyshen is there some solution from it? Because it's quite tough when you write sass code and make mistake you should wait for a long time (till 10s) to reload server and this situation my happens quite frequently,I thought that style lint might be nice solution but when I do `failsOnError:true` , and then do mistake in sass file my app doesn't rebuild. I would use your boilerplate in one of my project, but it last problem that I can't solve.
Thanks

**Comment by wellyshen** [comment]
Hi @maximusnikulin 

I'm still looking for how to solve the hot reloading of this issue, but I can recommend you to use inline style library for react.js. One of the library call [radium](https://formidable.com/open-source/radium/).

I personal use the inline style with react.js, you might ask me why don't use the library in the starter kit, it's because I need to consider to the general use case for most ppl, but I need to say inline style works great with react and hot reloading :)

**Comment by wellyshen** [comment]
@maximusnikulin 

It is a bug of webpack-isomorphic-tools, now it has been fixed ([detail](https://github.com/halt-hammerzeit/webpack-isomorphic-tools/issues/116#event-843473342)). 

If you don't want to stop the hot reloading process of .scss error, please turn the stylelint `failOnError` off from webpack config file, like below :

```
 new StyleLintPlugin({
      syntax: 'scss',
      failOnError: false,      // Disable style lint error terminating here
    }),
```
