### ISSUE TITLE
Feature Request: @svgr/webpack for SVGs are React Components

### ISSUE THREAD

**Issue by wshamim** [wellyshen/react-cool-starter#223]
I really like your starter but I got stuck in this minor thing. 

This will help in using SVGs are react components and make SVGs easy to import and use it in our components.

**Comment by joshuat** [comment]
Is there a benefit to @svgr/webpack over [babel-plugin-inline-react-svg](https://github.com/airbnb/babel-plugin-inline-react-svg)?

I only ask because I ran into this issue a few months ago as well and found that much easier to implement into the existing system than anything else. Just install and add it to your babel plugins array.

**Comment by wellyshen** [comment]
@wshamim Wow it's a cool library. But some people are using .svg with img tag some prefer svg component. So as a start-kit I think it's an optional but not must.
