### ISSUE TITLE
subroute not fetching route props using withRouter

### ISSUE THREAD

**Issue by dayrlism10** [wellyshen/react-cool-starter#233]
### Expected Behavior

-receiving route props for react router config

### Actual Behavior

-did not pass on route props even i change the route config into this way or import also withRouter.

 routes.js
```
render: (props: any) => <AsyncLayouts {...props} />
```

pages that to receive {this.renderLayouts(route.routes)}
```
export default compose(withRouter)(Layouts);
```

### Your Environment

- Client OS: Mac
- Browser and its version: 75.0.3770.100
- Version of node: v10.16.0

**Comment by wellyshen** [comment]
@dayrlism10 I will spend time to look into it.

**Comment by wellyshen** [comment]
@dayrlism10 How can I reproduce it?

**Comment by dayrlism10** [comment]
from the subroute page component, you won't be able to call `this.props.route`

**Comment by wellyshen** [comment]
@dayrlism10 How did you construct your `sub-route` any example?

**Comment by wellyshen** [comment]
@dayrlism10 It should be fixed by [pass `props` for async pages](https://github.com/wellyshen/react-cool-starter/blob/master/src/pages/Home/index.js#L12). You can try the latest [version](https://github.com/wellyshen/react-cool-starter/releases/tag/v2.9.4). You can also visit [react-router-config](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config) for more information.

**Comment by dayrlism10** [comment]
awesome, it work
