### ISSUE TITLE
question: why don't use renderToNodeStream instead of renderToString?

### ISSUE THREAD

**Issue by hienhuynhtm** [wellyshen/react-cool-starter#234]
Hi guys,
I love this boilerplace, very clean. But I have a question about **react-dom/server**

**Why don't we use renderToNodeStream instead of renderToString?**

> Rendering to a stream can reduce the time to first byte (TTFB) for your content, sending the beginning of the document down the wire to the browser before the next part of the document has even been generated. All major browsers will start parsing and rendering the document earlier when the content is streamed from the server this way.

```
import { renderToNodeStream } from "react-dom/server"
import MyPage from "./MyPage"app.get("/", (req, res) => {
  res.write("<!DOCTYPE html><html><head><title>My Page</title></head><body>");
  res.write("<div id='content'>"); 
  const stream = renderToNodeStream(<MyPage/>);
  stream.pipe(res, { end: false });
  stream.on('end', () => {
    res.write("</div></body></html>");
    res.end();
  });
});
```

**Comment by Rid** [comment]
I've made a fork to test this here: https://github.com/Rid/react-cool-starter

However there are a few issues:
1. Flickering on initial render as the CSS has to be loaded after renderToNodeStream due to CSS extraction
2. We're unable to minify the html as you need the complete rendered html in order to minify

You're welcome to fork my fork and see if you can address these issues some other way.

**Comment by wellyshen** [comment]
@hienhuynhtm @Rid Yea, we need to spend time to refactor the structure of SSR to implement `renderToNodeStream`. Do you guy want to send me a PR ;)

**Comment by hienhuynhtm** [comment]
@Rid I'll check your fork, then see that I can fix or not. Anyway, thanks for your support.
@wellyshen your project structure & coding standard looks great, I love it 👍

**Comment by mikejdegroot** [comment]
> @Rid I'll check your fork, then see that I can fix or not. Anyway, thanks for your support.
> @wellyshen your project structure & coding standard looks great, I love it 👍

Hey guys did this fork ever get fixed? I'm keen to switch over to renderToNodeStream also

**Comment by coder8338** [comment]
@mikejdegroot I haven't done anything with this project in a while as I've not had time to port my own install over to typescript yet.

My fork is using the older javascript version, so you might need to start this again from scratch.

**Comment by Rid** [comment]
@mikejdegroot I haven't done anything with this project in a while as I've not had time to port my own install over to typescript yet.

My fork is using the older javascript version, so you might need to start this again from scratch.

**Comment by mikejdegroot** [comment]
ok no worries, i'll try and take a look soon. my fork is on the JS version as well. Thanks for getting back to me

**Comment by wellyshen** [comment]
@mikejdegroot, Thank you, I will take time to survey it.

**Comment by amerllica** [comment]
In my implementation I started by using this repo, but I changed many things, for example for CSS I added `@Material/styles` JSS, so, if I wanna create CSS from server it is impossible for me to use stream rendering, because after the `renderToString` finished its work, I could grab server CSS and inject it to HTML.

**Comment by wellyshen** [comment]
Due to the [support of pre-fetching/pre-loading](https://loadable-components.com/docs/server-side-rendering/#prefetching), I think we won't implement this feature.
