### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by zanjs** [wellyshen/react-cool-starter#315]
Output:
‼ read ECONNRESET
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"

**Comment by wellyshen** [comment]
@zanjs Can you try to remove `node_modules` then reinstall it again?

**Comment by zanjs** [comment]
@wellyshen  Still wrong!

**Comment by wellyshen** [comment]
@zanjs I think this error was come from this [plugin](https://github.com/wellyshen/react-cool-starter/blob/054df8d9bdc86fa2b225b3fbac887627810c0b1a/tools/webpack/config.babel.js#L65). It's incompatible with your OS (I am OK with it, so I don't know the root case...). I use the new [one](https://github.com/tcoopman/image-webpack-loader) instead of it. You can try the latest commit version.
