### ISSUE TITLE
Hot update reducers on server side

### ISSUE THREAD

**Issue by maximusnikulin** [wellyshen/react-cool-starter#4]
First of all I want to thank you for this awesome boilerplate.
I run server with store which contains initial state from my reducers.
But when I change initial state in one of my reducers, it doesn't update.
I was trying to achieve reloading with nodeman. It watched folder with reducers and reload when they change, but nodemon reload server too slow.
There are some solutions for it such as piping, chokidar and so on.
It needs Browsersync also.
It would be great if you added it in this boilerplate.
Thanks.

**Comment by wellyshen** [comment]
Hey @maximusnikulin,

Thank you for your suggestion, I will start to survey it :)

**Comment by wellyshen** [comment]
Hi @maximusnikulin I already solve this issue. Now the hot reload works great for the reducers. Actually the issue is caused by the mechanism of preventing double fetching data in the action creator. You can see how I solving this problem [here](https://github.com/wellyshen/react-cool-starter/blob/master/src/containers/Home/action.js).

By the way I have updated the starter kit to [v1.3.0](https://github.com/wellyshen/react-cool-starter/releases/tag/v1.3.0) now it supports dynamic routing, async reducer and more ;)

**Comment by maximusnikulin** [comment]
That's perfect news!!! Thanks a lot!!! I will try it as soon as I can, thanks;)
