### ISSUE TITLE
Route-based code splitting

### ISSUE THREAD

**Issue by pkid169** [wellyshen/react-cool-starter#49]
Hi,

Sorry for the beginner question, does this setup support code splitting out of the box (i.e. different JS bundle per page)? If not, how can I go about doing that?

This is a terrific package by the way. I've been looking around and this is by far the most updated and cleanest setup. Can't wait to dig further into it.

Cheers

**Comment by wellyshen** [comment]
Hi @pkid169,

I removed the code splitting, because I don't have better solution for it running with react-router v4 on server-side, I will do the code splitting in the future.

By the way, you can do the code-splitting by refer the [docs](https://reacttraining.com/react-router/web/guides/code-splitting)
