### ISSUE TITLE
What is hook.js and what is its benefits?

### ISSUE THREAD

**Issue by amerllica** [wellyshen/react-cool-starter#599]
Just like I said, I read several starters and studied many implementations. I cannot understand what does the `hooks.js` do?

I had no problem until installing [`tailwindcss`](https://tailwindcss.com/docs/installation). By the docs guides, I add the `require('tailwindcss'),` to the `postcss.config.js` file and got this error:

```bash
/home/amerllica/WebstormProjects/heja/node_modules/css-modules-require-hook/node_modules/postcss/lib/lazy-result.es6:319
                throw new Error(
                      ^
Error: Use process(css).then(cb) to work with async plugins
    at LazyResult.sync (/home/amerllica/WebstormProjects/heja/node_modules/css-modules-require-hook/node_modules/postcss/lib/lazy-result.es6:319:23)
    at LazyResult.warnings (/home/amerllica/WebstormProjects/heja/node_modules/css-modules-require-hook/node_modules/postcss/lib/lazy-result.es6:157:21)
    at fetch (/home/amerllica/WebstormProjects/heja/node_modules/css-modules-require-hook/lib/index.js:102:16)
    at hook (/home/amerllica/WebstormProjects/heja/node_modules/css-modules-require-hook/lib/index.js:125:18)
    at Object.cssModulesHook [as .css] (/home/amerllica/WebstormProjects/heja/node_modules/css-modules-require-hook/lib/attachHook.js:16:20)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/amerllica/WebstormProjects/heja/src/app/index.tsx:10:1)
[nodemon] app crashed - waiting for file changes before starting...
```

Then I look for the [`css-modules-require-hook`](https://github.com/css-modules/css-modules-require-hook) and I see a bad thing :man_facepalming: My GOD. this library is for 2 years ago.

Here are a few questions:

 1. what is `hooks.js`?
 2. what does `hooks.js` do?
 3. why reading the `postcss` configuration is not in the [Webpack config](https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/config.babel.js)?
 4. what does `css-modules-require-hook` do?
 5. what does `asset-require-hook` do?
 6. is it possible to omit the `hooks.js` and add its configurations into [Webpack config](https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/config.babel.js)?

**Comment by wellyshen** [comment]
@amerllica Regarding to your question:

- `hook.js`: a module for setting `css-modules-require-hook` and `asset-require-hook`. We can omit it once we have implemented server-side bundling for development and production.
- `css-modules-require-hook`: compiling css modules in runtime, so styles can work properly in SSR.
- `asset-require-hook`: handling the import of static files in runtime, so images can work properly in SSR.
- `postcss` configuration: I follow the [setup document](https://webpack.js.org/loaders/postcss-loader/#usage) I think most people are following this way, however you can [set it via webpack as well](https://webpack.js.org/loaders/postcss-loader/#plugins).

**Comment by amerllica** [comment]
Dear @wellyshen bro, I set it by using Webpack and everything became ok now. for this sentence:

> We can omit it once we have implemented server-side bundling for development and production.

When we will going to have a server build, we could use the `isomorphic-style-loader`. I use it in [this example](https://gitlab.com/amerllica/react-server-render-example). I know you are busy now. but when you have time. take a little glance at this example on the repo that I have in my mind.

I implemented this we have now in our minds to have in `react-cool-starter` last year. if you have a little glance at it maybe it could be inspiring to us. I used `webpack-hot-server-middleware` so the setting of **Webpack** should be an array. one for client one for the server.

**Comment by wellyshen** [comment]
@amerllica The `isomorphic-style-loader` can be one of the option. However I will find a way to eliminate the `hook.js` after migrating webpack to v6. Let's keep this issue for enhancement.

**Comment by theogravity** [comment]
is there a guide on how to make tailwind work with the current setup?

also what I don't like about `isopmorphic-style-loader` is that it writes the CSS directly onto the page, compared to the current approach where it references the appropriate stylesheet

**Comment by wellyshen** [comment]
@theogravity 

For tailwind, as my experience it's easy to be integrated with this starter by following its [documentation](https://tailwindcss.com/docs/installation) (see this [issue](https://github.com/wellyshen/react-cool-starter/issues/191)). If you have any problem, please let me know, I'm glad to help you.

For `isopmorphic-style-loader`, I think we're on the same page.

**Comment by theogravity** [comment]
@wellyshen Thanks for responding.

The issue you posted unfortunately has broken links. Is there a quick patch that I could apply to grasp what's required?

I also experimented with removing `css-modules-require-hook` entirely, but it seems the JS / html loads first before the CSS when I do it, causing a jarring re-render of unstyled to styled. I also noticed that you said you cannot do styles in SSR by removing the hook.

I still haven't figured out how the require hook prevents this from happening, but I understand that because it implements `require.extensions`, it's impossible to implement a solution to use `tailwind` with the require hook as it's an async plugin and `require.extensions` is sync by its nature.

I'm looking into just using babel-loader with a combo of plugins to see if that might resolve things, but also wanted to ask you if you had a high-level idea of what you would have done in place of `css-modules-require-hook`, so I can try the ideas out on my side.

**Comment by theogravity** [comment]
I think I better understand the behavior now for why removing `css-modules-require-hook` causes the CSS rendering issue.

When node.js encounters the `import './test.css'` line, it looks at `require.extensions` for the `css` definition, which is filled in by `css-modules-require-hook`.

As you stated above, `css-modules-require-hook` is using `postcss` to compile the style into a JS object to be consumed by the application directly. Having this hook allows immediate render of the server side HTML and style at the same time (I'm guessing the CSS is in the JS bundle at this point), whereas the stylesheets in the `head` tags are loaded async to the static content (most likely for client-based navigation when you go forward and return to the original page to save on an SSR trip).

I looked into `babel` as a potential alternative, but it ends up using [`pirates`](https://github.com/ariporad/pirates) which is a standardized way to hook into `request.extensions`, which wouldn't work out since the [node API is sync-only](https://github.com/ariporad/pirates/issues/53).

It really seems the only alternative is to render the CSS directly into the DOM since you'd be able to call the processors in an async fashion.

For more info which talks about `postcss` sync / async issues:

https://medium.com/@longho/the-postcss-ecosystem-issue-b549c47b1a9

**Comment by wellyshen** [comment]
@theogravity 

- For the tailwind: Sorry, I removed the example branch, I'll find time to show you again.
- For the hook: I will find a better solution for it when I migrate this starter to Webpack v5.

**Comment by theogravity** [comment]
@wellyshen No rush. In the end I went with next.js as it offers a lot of stuff that this framework has.

I still think your framework is cool, but I spent too many days fighting it to get tailwind to work and I needed a solution that just works.

**Comment by wellyshen** [comment]
@theogravity 

Sorry for that. Next.js is an encapsulated framework, it's really easy to use, great choice. However this starter more like a scaffolding for DIY users. Thank you for your feedback, I'll spend time to make this starter more easy to use. Keep enrich the ecosystem of React.js.

BTW, I also using Next.js for some of my projects, we can still discuss about it lol.

**Comment by theogravity** [comment]
Thank you for all your work @wellyshen - I understand not everyone has free time to work on their projects and it's a miracle that you've continued to update it for so long.

**Comment by amerllica** [comment]
@wellyshen, The Webpack v5 is officially released, by:

> @amerllica The isomorphic-style-loader can be one of the option. However I will find a way to eliminate the hook.js after migrating webpack to v6. Let's keep this issue for enhancement.

Do you have a plan to eliminate `hook.js`?

**Comment by wellyshen** [comment]
@amerllica Yea, I'm planing to eliminate the `hook.js`. It causes several limitations of postCSS plugins, but I might not do it soon, because I'm focusing on a new form library.

**Comment by amerllica** [comment]
@wellyshen, which form library? could you say that name?

**Comment by wellyshen** [comment]
@amerllica The `react-cool-form`. It's under developing.
