### ISSUE TITLE
Page Getting Refresh When I Navigate from Home to User (Router Issue)

### ISSUE THREAD

**Issue by Jay341997** [wellyshen/react-cool-starter#600]
Hey Guys,
I am facing a Routing issue for the older android version (<= 4.). The issue is page getting refresh when I navigate from one page to another (ex. Home page to User). If you want to see this issue use any emulator which has an android version <= 4. In my case, I have used the Galaxy S lll emulator in Chrome Inspector. It will very helpful if you guys look into this.

**Comment by amerllica** [comment]
Dear @Jay341997, I guess it is better to leave a question on Stack Overflow. because we use `react-router` and we just use it, none of these technologies for ours. for example, you can leave issue or question about a router on NextJS repo, because they have their own routing. but we, just use trend techs.

I hope my comment helps you. :rose:

**Comment by wellyshen** [comment]
@Jay341997 This is the issue of the browser compatibility of `react-router`. I suggest you search related issues or ask this question there.
