### ISSUE TITLE
`npm run start` yields "[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)" and never completes

### ISSUE THREAD

**Issue by jbeard4** [wellyshen/react-cool-starter#62]
`npm run start` yields the following output:

```
> react-cool-starter@2.2.0 start /home/jacob/workspace/projects/react-cool-starter
> better-npm-run start

running better-npm-run in /home/jacob/workspace/projects/react-cool-starter
Executing script: start

to be executed: nodemon ./index.js --exec babel-node 
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: index.js /home/jacob/workspace/projects/react-cool-starter/tools/webpack/**/* src/server.js src/utils/Html.js
[nodemon] starting `babel-node ./index.js`
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
```

`[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)` repeats indefinitely and never completes.

Tested on Ubuntu 16.04.

**Comment by wellyshen** [comment]
@jbeard4 Try to run `npm run build:client` before `npm run start` to solve this problem.

**Comment by jbeard4** [comment]
That fixed it. Thank you.

**Comment by Edgargmc** [comment]
i have this error.


`$ npm start

> react-cool-starter@2.2.0 start c:\projects\react\redux-react4
> better-npm-run start

running better-npm-run in c:\projects\react\redux-react4
Executing script: start

to be executed: "nodemon ./index.js --exec babel-node"
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: index.js c:\projects\react\redux-react4\tools\webpack/**/* src/server.js src/utils/Html.js
[nodemon] starting `babel-node ./index.js`
[webpack-isomorphic-tools] [error] asset not found: ./src/components/UserList/styles.scss
[webpack-isomorphic-tools] [error] asset not found: ./src/containers/Home/styles.scss
[webpack-isomorphic-tools] [error] asset not found: ./src/components/UserCard/styles.scss
[webpack-isomorphic-tools] [error] asset not found: ./src/containers/UserInfo/styles.scss
[webpack-isomorphic-tools] [error] asset not found: ./src/containers/NotFound/styles.scss
[webpack-isomorphic-tools] [error] asset not found: ./src/theme/normalize.css
[webpack-isomorphic-tools] [error] asset not found: ./src/containers/App/styles.scss
==> �  Listening at http://localhost:3000
webpack building...
==> �  Rendering routes error: TypeError: Cannot read property 'App' of undefined
GET / 404 3205.921 ms - 12
./src/client.js
Module build failed: Module failed because of a eslint error.

c:\projects\react\redux-react4\src\client.js
   1:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   2:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   3:27  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`


**Any ideas, please**

**Comment by wellyshen** [comment]
Hi @Edgargmc, Please refer to this [issue](https://github.com/wellyshen/react-cool-starter/issues/72#issuecomment-312468884)

**Comment by codeuniquely** [comment]
I just ran into this issue

Can you ADD the advice about running the client build before **START**  to the readme - because it absolutely works - its kinda frustrating to have to trawl through closed issues to find the fix

**Comment by martin2786** [comment]
Hi @codeuniquely the advice is already in the readme under the Troubleshooting section, maybe it can be mentioned somewhere at the start of the document instead of at the end?
