### ISSUE TITLE
Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

### ISSUE THREAD

**Issue by aagentah** [wellyshen/react-cool-starter#72]
Hi, So I successfully installed & built this project on my machine at work, but somehow my machine at home returns this error after running "yarn start:production".

`Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`

I looked online and people have mentioned it's an ".eslintrc" related problem, but I cannot find this file.
Any ideas?

Thank you in advance.

**Comment by ghost** [comment]
Awesome sauce. My first Github issue contribution. You must be on a Windows machine. By default, Windows machines use the invisible CRLF character to represent line breaks. Linux uses LF and the Airbnb based esLint rules the project follows expects LF. Here is how you can redownload the repo and not have this problem.
1. Enter  "git config --global core.autocrlf false" in the command line.
2. git clone <the-repo>
3. Open your text editor and before modifying any files, change the settings to use Linux line breaks instead of windows line breaks.
4. Everything should be working.

**Comment by aagentah** [comment]
Hi @HudsonHughes,

So I tried "git config --global core.autocrlf false"  in my git shell and cloned the project but it doesn't seem to have fixed the issue, the issue occurs when I run "yarn start:production" and errors before I have even made any changes, any thoughts?

Thanks!

**Comment by wellyshen** [comment]
I will upgrade the eslint from v3 to v4 soon (I'm waiting for the airbnb support eslint v4). Please wait to see it, which might fix the bug.

**Comment by aagentah** [comment]
@wellyshen no problem!

**Comment by danjonesdev** [comment]
Where are the rules for the linting set within this project? I believe setting 

`"rules": {
"linebreak-style": 0,
}`

will resolve this.
Thanks
