### ISSUE TITLE
Hot Reload wont work for server side rendering

### ISSUE THREAD

**Issue by kooinam** [wellyshen/react-cool-starter#81]
I would always get warning saying server side rendering is different from client side rendering in development after every change. I would need to manually restart node before this warning goes away. Apparently hot reload is not working for server side rendering. Any clue?

**Comment by wellyshen** [comment]
Hi @kooinam I didn't implement server-side hot reload for this starter. So, if you click the "refresh" button of browser you'll got the "chunk sum errors". I suggest you let hot reload updates the view instead of clicking the button during developing.

I didn't start survey the server-side hot reload for webpack 3 yet, but I found this [post](https://hackernoon.com/hot-reload-all-the-things-ec0fed8ab0), see if it can help you.

BTW, I'll start to survey the server-side hot reload then see if it's worth to be including in this starter. Thank you for your informing :)

**Comment by mrchief** [comment]
I've hot reload working for me but I'm using koa. I took this boilerplate and adopted it to use koa instead of express. @wellyshen Let me know if you'd be interested in that.

**Comment by wellyshen** [comment]
@mrchief Compare to koa, I'm the fan of express (actually I'm not study koa yet). But you are willing to fork and create a koa repo for those who want a server side hot-reloading. Then I will prompt it by adding a link on my README file.

**Comment by mrchief** [comment]
@wellyshen koa is created by same folks who created Express. I wouldn't bore you with details about Koa vs Express, there are plenty of well written articles already out there. :)

I'll do the fork and let you know. I'm still new to all this so your thoughts would be very welcome.
