### ISSUE TITLE
Do you need a dispatch in routes.js?

### ISSUE THREAD

**Issue by aagentah** [wellyshen/react-cool-starter#95]
For each page, it uses a dispatch for that page's action in the routes:

```
    loadData: (dispatch: Dispatch) => Promise.all([
      dispatch(fetchUsersIfNeeded()),
    ]),
```
My question is.. Why is this necessary when it is being called from "componentDidMount" in the page itself?

Thank you in advance!
Dan

**Comment by martin2786** [comment]
Hi @danjonesdev, please @wellyshen  correct me if I'm wrong but there's a dispatch on each route so that the server can fetch the data before loading the view, remember that this uses SSR so it's convenient to get the initial data before displaying the requested page in order to display a fully loaded page. the component will execute again on mount because a component can be reused and you can include it in a page that doesn't need that data as initial data. Also the FetchIfNeeded method it's checking if the data has been already loaded or not so if it has, it won't load it again.

**Comment by aagentah** [comment]
Thank you, That seems to make sense! @martin2786
